databaseChangeLog:
  - changeSet:
      id: 202310021300-gradebook-add-initial-values
      author: akujawa
      description: add initial values
      changes:
        - sqlFile:
            path: "db/changelog/202310021400-gradebook-add-initial-values.sql"
            dbms: "h2, postgresql"
            encoding: UTF-8
            endDelimiter: ;
            splitStatements: true
            stripComments: false